# Generated by Django 6.0.4 on 2026-04-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyblade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='private_key',
            new_name='key_hash',
        ),
    ]
