# Generated by Django 6.0.4 on 2026-04-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyblade', '0002_rename_private_key_key_key_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key_hash',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
