# Generated by Django 6.0.4 on 2026-04-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyblade', '0003_alter_key_key_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
