# Generated by Django 6.0.4 on 2026-04-13 15:52

import canstorage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the object. Must be unique across all objects in the can. May contain A-Z, a-z, 0-9, ., _, -, and well-formed paths, and cannot start with an underscore. Cannot be changed after creation.', max_length=255, validators=[canstorage.models.validate_object_name])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.CharField(max_length=20)),
                ('object_type_verbose', models.CharField(max_length=20)),
                ('object_type_verbose_plural', models.CharField(max_length=20)),
                ('_name_at_creation', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessControlList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user_permissions', models.PositiveSmallIntegerField(choices=[(7, 'Read, index, write'), (5, 'Read, index'), (4, 'Read only'), (0, 'No access')], default=0)),
                ('group_permissions', models.PositiveSmallIntegerField(choices=[(7, 'Read, index, write'), (5, 'Read, index'), (4, 'Read only'), (0, 'No access')], default=0)),
                ('others_permissions', models.PositiveSmallIntegerField(choices=[(7, 'Read, index, write'), (5, 'Read, index'), (4, 'Read only'), (0, 'No access')], default=0)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Can',
            fields=[
                ('name', models.CharField(help_text='A unique, permanent name for the can. May contain A-Z, a-z, 0-9, ., _, -. Must not start with a dot or underscore, or be "accounts", "admin", "api", "cans", "c3s", "favicon.ico", "media", or "static". Cannot be changed after creation.', max_length=64, primary_key=True, serialize=False, validators=[canstorage.models.validate_can_name])),
                ('description', models.TextField(blank=True, help_text='A note for the can. The description is shown to anyone with read access to the can.', null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('_name_at_creation', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('access_control_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canstorage.accesscontrollist')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='canstorage.object')),
                ('data', models.FileField(upload_to=canstorage.models._get_file_upload_path)),
                ('content_type', models.CharField(blank=True, help_text='Content/MIME type of the file. Inferred from file extension of object name by default.', max_length=64, null=True)),
            ],
            options={
                'default_permissions': (),
            },
            bases=('canstorage.object',),
        ),
        migrations.CreateModel(
            name='JSON',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='canstorage.object')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'JSON',
                'verbose_name_plural': 'JSONs',
                'default_permissions': (),
            },
            bases=('canstorage.object',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='canstorage.object')),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'default_permissions': (),
            },
            bases=('canstorage.object',),
        ),
        migrations.AddField(
            model_name='object',
            name='_can_at_creation',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_can_at_creation', to='canstorage.can'),
        ),
        migrations.AddField(
            model_name='object',
            name='can',
            field=models.ForeignKey(help_text='The parent can of the object. Cannot be changed after creation.', on_delete=django.db.models.deletion.CASCADE, to='canstorage.can'),
        ),
        migrations.AddField(
            model_name='object',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('can', 'name'), name='unique_can_name'),
        ),
    ]
