# Generated by Django 6.0.4 on 2026-04-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canstorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('Text', 'Text'), ('JSON', 'JSON'), ('File', 'File')], max_length=20),
        ),
    ]
