# Generated by Django 6.0.4 on 2026-04-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canstorage', '0002_alter_object_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
