# Generated by Django 6.0.4 on 2026-04-23 05:22

import canstorage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canstorage', '0003_alter_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.CharField(default=canstorage.models.generate_object_id, max_length=32, primary_key=True, serialize=False),
        ),
    ]
